main/urls.py
from cgitb import reset
from re import template
from django.urls import path,include
from .import views

#for main admin
from django.contrib.auth.urls import views as auth_views



urlpatterns = [
    path('contact_us',views.contact_us,name='contact_us'),
    path('',views.index,name='indexHome'),

    # main_Admin paths
    path('main_admin',views.main_admin,name='main_admin'),
    path('export_user_csv',views.export_user_csv,name='export_user_csv'),
    path('user_change/<str:user_name>',views.user_change,name='user_change'),
    path('delete_user',views.delete_user,name='delete_user'),
    path('add_new_user',views.Add_New_User,name='add_new_user'),
    path('add_device',views.add_device,name='add_device'),
    path('delete_device',views.delete_device,name='delete_device'),
    path('loadmoreUser',views.load_more_Users,name='loadmoreUser'),




    # path('account/',include('django.contrib.auth.urls')),
    # path('account/change_password',auth_views.PasswordChangeView.as_view()),
    path('test',views.test,name='test'),





]

vdas/urls.py
import imp
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include

# from . import views
 
# For Media managing
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/',include('django.contrib.auth.urls')),
    path('member/',include('member.urls')),
    path('device/',include('device.urls')),
    path('',include('main.urls')),

    # path('',views.index,name='home'),
    
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)


admin.site.index_title = 'Vehcile Data Acquisition System'
admin.site.site_header = 'FYP Adminisntration '
admin.site.site_title = 'F Y P'

main/models.py
from django.db import models

# Create your models here.
# class contact_us_db(models.Model):
#     msg_id = models.AutoField(primary_key=True) Foreign key
#     msg_id = models.AutoField(primary_key=True)
#     name = models.CharField(max_length=70,default="")
#     email = models.CharField(max_length=70,default="")
#     phone = models.CharField(max_length=70,default="")
#     desc = models.CharField(max_length=500,default="")

#     def __str__(self):
#         return self.name


# class sensor_db(models.Model):
    # white_box_id = models.AutoField(primary_key=True) Foreign key
    # temperature = models.IntegerField()
    # Humidity = models.IntegerField()
    # CO = models.IntegerField()
    # Light = models.IntegerField()
    # Latitude = models.IntegerField()
    # Longitude = models.IntegerField()

    # def __str__(self):
    #     return self.white_box_id

main/forms.py
from django import forms 
from django.core.validators import MaxValueValidator
from traitlets import default


class DevicesForm (forms.Form):
    # device_id = forms.
    vehicle_no = forms.NumberInput()
    route_name = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control my-2'}))
    temperature = forms.BooleanField(initial= False)
    carbon_mono = forms.BooleanField(initial= False)
    humidity = forms.BooleanField(initial= False)
    light = forms.BooleanField(initial= False)
    noise = forms.BooleanField(initial= False)
    langitude = forms.BooleanField(initial= False)
    latitude = forms.BooleanField(initial= False)


   

    # class  Meta:
    #     model = User
    #     fields = ('username','email','first_name','last_name','password1','password2')
    # def __init__(self, *args,**kwargs):
    #     super(RegisterUserForm,self).__init__(*args,*kwargs)           
    #     self.fields['username'].widget.attrs['class'] = 'form-control my-2'
    #     self.fields['password1'].widget.attrs['class'] = 'form-control my-2'
    #     self.fields['password2'].widget.attrs['class'] = 'form-control my-2'

member/forms.py
from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django import forms 

class RegisterUserForm (UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control my-2'}))
    last_name = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control my-2'}))

    class  Meta:
        model = User
        fields = ('username','email','first_name','last_name','password1','password2')
    def __init__(self, *args,**kwargs):
        super(RegisterUserForm,self).__init__(*args,*kwargs)           
        self.fields['username'].widget.attrs['class'] = 'form-control my-2'
        self.fields['password1'].widget.attrs['class'] = 'form-control my-2'
        self.fields['password2'].widget.attrs['class'] = 'form-control my-2'
            
            


# class PasswordChangingform (PasswordChangeForm):
    # old_password = forms.PasswordInput(widget=forms.PasswordInput(attrs={'class':'form-control','type': 'password'} ))
    # new_password1 = forms.PasswordInput(widget=forms.PasswordInput(attrs={'class':'form-control my-2'}))
    # new_password2 = forms.PasswordInput(widget=forms.PasswordInput(attrs={'class':'form-control my-2'}))

    # class  Meta:
    #     model = User
    #     fields = ('old_password','new_password1','new_password2',)
    # def __init__(self, *args,**kwargs):
    #     super(PasswordChangingform,self).__init__(*args,*kwargs)           
    #     self.fields['old_password'].widget.attrs['class'] = 'form-control my-2'
    #     self.fields['new_password1'].widget.attrs['class'] = 'form-control my-2'
    #     self.fields['new_password2'].widget.attrs['class'] = 'form-control my-2'   

main/views.py
from distutils.command.build_scripts import first_line_re
from django.shortcuts import redirect, render
from requests import request
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm
from django.urls import reverse_lazy
from member.forms import RegisterUserForm
from device.forms import DevicesForm
from device.models import devices,sensors
from django.http import HttpResponse, JsonResponse
import csv
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
# from . models import contact_us_db
from json import dumps
#For User model
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from urllib3 import HTTPResponse
from django.core.paginator import Paginator,EmptyPage
from django.core import serializers



# Create your views here.

def index(request):

    return render (request,'main/index.html')


    

@login_required
def main_admin(request):
    if request.user.is_superuser:
        # Getting All user
        User = get_user_model()
        rev_users = User.objects.all().order_by('-id')
        users = Paginator(rev_users,15)
        page_list = request.GET.get('page')
        users=users.get_page(page_list)
        # users = User.objects.all().order_by('-id')[:15]
        print(users)
        totalUser = User.objects.all().count()
        # Adding new Users 
        # if request.method!='POST':
        #     form = RegisterUserForm()   
        # else:
        #     form = RegisterUserForm(request.POST)
        #     if form.is_valid():
        #         form.save()
        #         djusername = form.cleaned_data['username']
        #         djpassword = form.cleaned_data['password1']
        #         djemail = form.cleaned_data['email']
        #         djf_name = form.cleaned_data['first_name']
        #         djl_name = form.cleaned_data['last_name']
                
        #         user = authenticate(username = djusername, password = djpassword, email = djemail, first_name = djf_name, last_name = djl_name )
            #UserRegistrationForm
        UserRegform = RegisterUserForm()
            # Device Form
        dev_form = DevicesForm()

        # AllDevicesList
        # alldevices = devices.objects.all() 
        rev_devices = devices.objects.all().order_by('-device_id')
        device_page = Paginator(rev_devices,15)
        page_list = request.GET.get('page')
        device_page = device_page.get_page(page_list)
        totaldevices = devices.objects.all().count()


            
       
    
            
           
        context = {'users':users,'UserRegform':UserRegform,'devices':device_page, 'deviceForm':dev_form,'totalUser':totalUser,'totaldevices':totaldevices}
        # context = {'users':users,'form':form,'devices':alldevices, }

        return render (request,'main/main_admin.html',context)
    else:
        return render (request,'member/index.html')

def Add_New_User(request):
    if request.method=='POST':
            form = RegisterUserForm(request.POST)
            if form.is_valid():
                form.save()
                djusername = form.cleaned_data['username']
                djemail = form.cleaned_data['email']
                djf_name = form.cleaned_data['first_name']
                djl_name = form.cleaned_data['last_name']
                djpassword = form.cleaned_data['password1']
                djpassword2 = form.cleaned_data['password2']      
                user = authenticate(username = djusername, password = djpassword, email = djemail, first_name = djf_name, last_name = djl_name,password2=djpassword2 )
                user.save()
                #alldevices = devices.objects.values()
                #devicesList = list(alldevices)
                users = User.objects.values().order_by('-id')[:15]
                userList15 = list(users)
            # user = authenticate(username= djusername,password=djpassword)
            # login(request,user)
            # messages.success(request, 'Successfully registered and loged in')
            return JsonResponse({'status':1,'usersList':userList15})

    else:
          return JsonResponse({'status':0})

def delete_user(request):
    if request.method=='POST':
        user = request.POST['username']
        del_user  = User.objects.get(username=user)
        users = User.objects.values().order_by('-id')[:15]
        userList15 = list(users)
    
        del_user.delete()
        return JsonResponse({'status':1,'usersList':userList15})

    else:
          return JsonResponse({'status':0})
  

def contact_us(request):
    #   if request.method =='POST':
    #     djname = request.POST.get('name','')
    #     djemail = request.POST.get('email','')
    #     djphone = request.POST.get('phone','')
    #     djdesc = request.POST.get('desc','')
        # contact = contact_us_db(name=djname,email= djemail, phone= djphone, desc = djdesc)
        # contact.save()

    return render (request,'main/contact_us.html',{})
def test(request):

            
        
    context = {'deviceForm'}
    # context = {'users':users,'form':form,'devices':alldevices, }

    return render (request,'main/test.html',context)


def add_device(request):
    if request.method=='POST':
        device_form = DevicesForm(request.POST)    
        if device_form.is_valid():
            # vehicle_no route_name  temperature carbon_mono  humidity light noise  langitude latitude
            dj_v_no = request.POST['vehicle_no']
            dj_r_name = request.POST['route_name']
            dj_temp = True if request.POST.get('temperature') == "on" else False
            dj_co = True if request.POST.get('carbon_mono') == "on" else False
            dj_hum = True if request.POST.get('humidity') == "on" else False
            dj_light = True if request.POST.get('light') == "on" else False
            dj_noise = True if request.POST.get('noise') == "on" else False
            dj_long = True if request.POST.get('latitude') == "on" else False
            dj_lat = True if request.POST.get('latitude') == "on" else False

            dev = devices(vehicle_no=dj_v_no, route_name = dj_r_name,  temperature= dj_temp, carbon_mono = dj_co,  humidity = dj_hum, light = dj_light,  noise = dj_noise, langitude = dj_long, latitude = dj_lat)
            dev.save()
            alldevices = devices.objects.values()
            devicesList = list(alldevices)
           
            return JsonResponse({'status':1,'devicesList':devicesList})
        else:
            return JsonResponse({'status':0})

def delete_device(request):
    if request.method=='POST':
        dj_dev_id = request.POST.get('dj_dev_id',False)
        del_dev  = devices.objects.get(device_id=dj_dev_id)
        del_dev.delete()
        alldevices = devices.objects.values()
        devicesList = list(alldevices)
        return JsonResponse({'status':1,'devicesList':devicesList})
    else:
        return JsonResponse({'status':0})
   
def load_more_Users(request):
    if request.method=='POST':
        offset = int(request.POST['offset'])
        limit = 10
        serial  = offset+limit
        total_users = User.objects.all().count()
        print(total_users)
        if offset>=total_users:
            return JsonResponse({'status':0,})
        else:
            allusers = User.objects.all().order_by('-id')[offset:offset+limit]         
            userList = serializers.serialize('json',allusers)
      
        return JsonResponse({'usersList':userList,'serial':serial})


def user_change(request,user_name):
    User  = get_user_model().objects.get(username=user_name)
    if request.method == 'POST':
        User.username  = request.POST.get('username')
        User.first_name  = request.POST.get('first_name')
        User.last_name  = request.POST.get('last_name')
        User.email  = request.POST.get('email')
        User.is_staff = True if request.POST.get("is_staff") == "on" else False
        User.is_active = True if request.POST.get("is_active") == "on" else False
        User.is_superuser = True if request.POST.get("is_superuser") == "on" else False


        # newPass = request.POST.get('password')
        # User.set_password(newPass)
        

        User.save()
       
   
    context = {'user':User}
    return render (request,'main/user_change.html',context)


def register_user(request):
    if request.method=='POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            djusername = form.cleaned_data['username']
            djpassword = form.cleaned_data['password1']
            djemail = form.cleaned_data['email']
            djf_name = form.cleaned_data['first_name']
            djl_name = form.cleaned_data['last_name']
            
            user = authenticate(username = djusername, password= djpassword, email = djemail, first_name = djf_name, last_name = djl_name )
            # user = authenticate(username= djusername,password=djpassword)
            login(request,user)
            # print(user)
            # print(form)
            messages.success(request, 'Successfully registered and loged in')
            return redirect('member_home')

    else:
        form = RegisterUserForm()        
    return render (request,'member/register.html' ,{'form':form})

# def save_user_change(request):
#     User  = get_user_model().objects.get(id=User.user_id)
#     print(User.username)
#     if request.method == 'POST':
#         dj_f_name  = request.POST.filter('first_name',instance = User)
#         dj_l_name  = request.POST.filter('last_name',instance = User)
#         save = get_user_model(first_name = dj_f_name,last_name = dj_l_name)
#         print(save.username)
#         save.save()
#         print(save.username)

main/templates/main/add_new_user.html
{% extends 'main/admin_basic.html' %}
{% block title%}Add new user{% endblock%}
{% block body%}
<div class="row d-flex my-5 justify-content-center">
    <div class="col-lg-8 col-10 p-5 rounded shadow ">

       
        <h1 class="mb-5 text-center">Add new User</h1>
        {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}

    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}

{% endif %}


        <form method="POST" action="add_new_user">
            {{form.as_p}}
            {% csrf_token %}
            <br>
            <button type="submit" class="btn btn-outline-primary">Submit</button>
        </form>
    </div>
</div>

{% endblock %}

main/templates/main/ajax.html
<script>

   // AddUserAjaxEffect
   $(document).ready(function (e) {

$('#btn_userSave').click(function (e) {

e.preventDefault();
console.log('userAjax');
output = "";
$('#dev_save_text').addClass('hide');
      let username = $('#id_username').val();
      let email = $('#id_email').val();
      let first_name = $('#id_first_name').val();
      let last_name = $('#id_last_name').val();
      let password1 = $('#id_password1').val();
      let password2 = $('#id_password2').val();
      let csrf = $("input[name=csrfmiddlewaretoken]").val();

      var mydata = { 'username': username, 'email': email, 'first_name': first_name, 'last_name': last_name,  'password1': password1, 'password2': password2, 'csrfmiddlewaretoken': csrf };
      $.ajax({
         url: "{% url 'add_new_user' %}",
         method: "POST",
         data: mydata,
   //       beforeSend:function(){
   // $('#btn_load_more').addClass('disabled').text('loading');
   // },
         success: function (res) {

            ul = res.usersList;

            for (i = 0; i < ul.length; i++) {
                  output += "<tr><td>" +
                  ul[i].id + "</td><td>"
                  + ul[i].username + "</td><td>"
                  + ul[i].first_name + "</td><td>"
                  + ul[i].last_name + "</td><td>"
                  + ul[i].email + "</td><td>"
                  + "</td><td><a href='user_change/"+ ul[i].username+"'class='btn btn-sm ms-3  btn-primary' role='button'>View<i class='fa-solid ms-1 fa-pen-to-square'></i></a></td><td><button type='button' class='btn btn-sm btn-danger' data-bs-toggle='modal' data-bs-target='#btn_del_modal' data-bs-whatever=" + ul[i].username + "  id='btn_del' >Delete<i class='fa-solid ms-1 fa-trash-can'></i></button></td></tr>";

            }

            $('#user_tbody').html(output);

         }
      });

   });
});
   


   //DeleteUserAjax
//  DeleteUserModal 
var deleteModal = document.getElementById('btn_del_modal')
    deleteModal.addEventListener('show.bs.modal', function (event) {
        var button = event.relatedTarget;
        var user_name = button.getAttribute('data-bs-whatever');
        var modalTitle = deleteModal.querySelector('.modal-title');
        var modalBodyText = deleteModal.querySelector('.modal-body #del_id');
        modalTitle.textContent = " Delete '" + user_name + "' ?";
        modalBodyText.textContent = " Are you sure to delete user with username' " + user_name + "' ? ";
        del_user_id = document.getElementById('del_user_btn');
      //   var btn_link = "delete_user/" + user_name;
      //   del_user_id.textContent = " Delete ' " + user_name + " '";
      //   del_user_id.setAttribute("href", btn_link);
    
      $(document).ready(function (e) {

$('#del_user_btn').click(function (e) {

e.preventDefault();
console.log('DeleteuserAjax');
output = "";
      let del_userBtn = $('#btn_del_user')
      let username = user_name;
      console.log(user_name);
      let csrf = $("input[name=csrfmiddlewaretoken]").val();

      var mydata = { 'username': user_name, 'csrfmiddlewaretoken': csrf };
      $.ajax({
         url: "{% url 'delete_user' %}",
         method: "POST",
         data: mydata,
   //       beforeSend:function(){
   // $('#btn_load_more').addClass('disabled').text('loading');
   // },
         success: function (res) {
            console.log(res)
            ul = res.usersList;

            for (i = 0; i < ul.length; i++) {
                  output += "<tr><td>" +
                  ul[i].id + "</td><td>"
                  + ul[i].username + "</td><td>"
                  + ul[i].first_name + "</td><td>"
                  + ul[i].last_name + "</td><td>"
                  + ul[i].email + "</td><td>"
                  + "</td><td><a href='user_change/"+ ul[i].username+"'class='btn btn-sm ms-3  btn-primary' role='button'>View<i class='fa-solid ms-1 fa-pen-to-square'></i></a></td><td><button type='button' class='btn btn-sm btn-danger' data-bs-toggle='modal' data-bs-target='#btn_del_modal' data-bs-whatever=" + ul[i].username + "  id='btn_del_user' >Delete<i class='fa-solid ms-1 fa-trash-can'></i></button></td></tr>";

            }

            $('#user_tbody').html(output);

         }
      });

   });
});
});

   // DeviceSaveAjax
   $('#btn_device_save').click(function (e) {

      e.preventDefault();
      output = "";
      $('#dev_save_text').addClass('hide');
      let dev_v_no = $('#id_vehicle_no').val();
      let dev_r_name = $('#id_route_name').val();
      let dev_temp = $('#id_temperature').val();
      let dev_car_mono = $('#id_carbon_mono').val();
      let dev_humi = $('#id_humidity').val();
      let dev_light = $('#id_light').val();
      let dev_noise = $('#id_noise').val();
      let dev_long = $('#id_langitude').val();
      let dev_lat = $('#id_latitude').val();
      let csrf = $("input[name=csrfmiddlewaretoken]").val();


      var mydata = { 'vehicle_no': dev_v_no, 'route_name': dev_r_name, 'temperature': dev_temp, 'carbon_mono': dev_car_mono, 'humidity': dev_humi, 'light': dev_light, 'noise': dev_noise, 'langitude': dev_long, 'latitude': dev_lat, 'csrfmiddlewaretoken': csrf };
      $.ajax({
         url: "{% url 'add_device' %}",
         method: "POST",
         data: mydata,
         success: function (data) {
            // $('#dev_save_text').html(data.status);

            if (data.status == 1) {
               $('#dev_success_alert').removeClass('hide');
               $('#dev_error_alert').addClass('hide');


            }
            else if (data.status == 0) {
               $('#dev_error_alert').removeClass('hide');
               $('#dev_success_alert').addClass('hide');


            }

            dev = data.devicesList;

            for (i = 0; i < dev.length; i++) {
               output += "<tr><td>" +
                  dev[i].device_id + "</td><td>"
                  + dev[i].vehicle_no + "</td><td>"
                  + dev[i].route_name + "</td><td>"
                  + dev[i].temperature + "</td><td>"
                  + dev[i].carbon_mono + "</td><td>"
                  + dev[i].humidity + "</td><td>"
                  + dev[i].light + "</td><td>"
                  + dev[i].noise + "</td><td>"
                  + dev[i].langitude + "</td><td>"
                  + dev[i].latitude + "</td><td><a href='#' class='btn btn-sm ms-3  btn-primary' role='button'>Edit<i class='fa-solid ms-1 fa-pen-to-square'></i></a></td><td><button type='button' class='btn btn-sm btn-danger' data-bs-toggle='modal' data-bs-target='#btn_del_dev_modal' data-bs-whatever=" + dev[i].device_id + "  id='btn_dev_del' >Delete<i class='fa-solid ms-1 fa-trash-can'></i></button></td></tr>";


            }

            $('#table_body').html(output);
            document.getElementById("dev_form").reset();
            document.getElementById("device_form").classList.add("hide");
         }
      });

   });

   // deleteDevice

   var deleteDevModal = document.getElementById('btn_del_dev_modal')
   deleteDevModal.addEventListener('show.bs.modal', function (event) {
      var button = event.relatedTarget;
      var device_del_id = button.getAttribute('data-bs-whatever');
      var modalTitle = deleteDevModal.querySelector('.modal-title');
      var modalBodyText = deleteDevModal.querySelector('.modal-body #del_dev_id');
      modalTitle.textContent = " Delete '" + device_del_id + "' ?";
      modalBodyText.textContent = " Are you sure to delete device with id' " + device_del_id + "' ? ";


      // ajax functionality
      $('#del_dev_btn').click(function (e) {
         output = "";
         let csrf = $("input[name=csrfmiddlewaretoken]").val();

         myDelData = { 'dj_dev_id': device_del_id, 'csrfmiddlewaretoken': csrf };

         $.ajax({
            url: "{% url 'delete_device' %}",
            method: "POST",
            data: myDelData,
            success: function (data) {
               if (data.status == 1) {
                  $('#dev_success_alert').removeClass('hide');
                  $('#dev_error_alert').addClass('hide');

               }
               else if (data.status == 0) {
                  $('#dev_error_alert').removeClass('hide');
                  $('#dev_success_alert').addClass('hide');

               }

               dev = data.devicesList;
               for (i = 0; i < dev.length; i++) {
                  output += "<tr><td>" +
                     dev[i].device_id + "</td><td>"
                     + dev[i].vehicle_no + "</td><td>"
                     + dev[i].route_name + "</td><td>"
                     + dev[i].temperature + "</td><td>"
                     + dev[i].carbon_mono + "</td><td>"
                     + dev[i].humidity + "</td><td>"
                     + dev[i].light + "</td><td>"
                     + dev[i].noise + "</td><td>"
                     + dev[i].langitude + "</td><td>"
                     + dev[i].latitude + "</td><td><a href='#' class='btn btn-sm ms-3  btn-primary' role='button'>Edit<i class='fa-solid ms-1 fa-pen-to-square'></i></a></td><td><button type='button' class='btn btn-sm btn-danger' data-bs-toggle='modal' data-bs-target='#btn_del_dev_modal' data-bs-whatever=" + dev[i].device_id + "  id='btn_dev_del' >Delete<i class='fa-solid ms-1 fa-trash-can'></i></button></td></tr>";

               }

               $('#table_body').html(output);

            }
         }); //Ajax closed

      });// main func

   });//modal func END

   //Load More Users
   $(document).ready(function (e) {

$('#btn_load_more').click(function (e) {

e.preventDefault();
output = "";
let csrf = $("input[name=csrfmiddlewaretoken]").val();
// href="{%url 'main_admin'%}?page={{devices.num_page}}"
var offset = $('.usersCount').length;
var ser=undefined;
var mydata = { 'offset':offset,'csrfmiddlewaretoken': csrf };
$.ajax({
   url: "{% url 'loadmoreUser' %}",
   method: "POST",
   data: mydata,
   dataType:'json',
   beforeSend:function(){
   $('#btn_load_more').addClass('disabled').text('loading');
   },
   success: function (res) {
      if (res.status==0){
   $('#btn_load_more').addClass('disabled').text('No more users');

      }
      else{
   
            var output = '';
            var json_data = $.parseJSON(res.usersList);
               ser = res.serial-10;
            $.each(json_data,function(index,data){
               ser++;


               output += "<tr class='usersCount'><th scope='row'>"+ser+"</th><td>"+data.fields.username+"</td><td>"+data.fields.first_name+"</td><td>"+data.fields.last_name+"</td><td>"+data.fields.email+"</td><td><a href='user_change/"+data.fields.username+"'type='button' class='btn ms-3  btn-primary'>View<i class='fa-solid ms-1 fa-pen-to-square'></i></a> </td><td><button type='button' class='btn btn-danger' data-bs-toggle='modal'data-bs-whatever="+data.fields.username+" id='btn_del_user' data-bs-target='#btn_del_modal'>Delete<i class='fa-solid ms-1 fa-trash-can'></i></button></td></tr>";
               console.log(data.fields.id);
               
            });
         $('#user_tbody').append(output);
         $('#btn_load_more').removeClass('disabled').text('Load more');
      }

      // dev = data.devicesList;

      // for (i = 0; i < dev.length; i++) {
      //    output += "<tr><td>" +
      //       dev[i].device_id + "</td><td>"
      //       + dev[i].vehicle_no + "</td><td>"
      //       + dev[i].route_name + "</td><td>"
      //       + dev[i].temperature + "</td><td>"
      //       + dev[i].carbon_mono + "</td><td>"
      //       + dev[i].humidity + "</td><td>"
      //       + dev[i].light + "</td><td>"
      //       + dev[i].noise + "</td><td>"
      //       + dev[i].langitude + "</td><td>"
      //       + dev[i].latitude + "</td><td><a href='#' class='btn btn-sm ms-3  btn-primary' role='button'>Edit<i class='fa-solid ms-1 fa-pen-to-square'></i></a></td><td><button type='button' class='btn btn-sm btn-danger' data-bs-toggle='modal' data-bs-target='#btn_del_dev_modal' data-bs-whatever=" + dev[i].device_id + "  id='btn_dev_del' >Delete<i class='fa-solid ms-1 fa-trash-can'></i></button></td></tr>";


      // }

      // $('#table_body').html(output);

   },
   
});

});
});






</script>